apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-neutron-netns-exporter
data:
  openstack-config.yaml: |
    openstack:
      auth_url: {{ required ".Values.netns.openstack.auth_url missing" .Values.netns.openstack.auth_url }}
      user_domain_name: {{ required ".Values.netns.openstack.domain missing" .Values.netns.openstack.domain }}
      project_domain_name: {{ required ".Values.netns.openstack.project_domain missing" .Values.netns.openstack.project_domain }}
      project_name: {{ required ".Values.netns.openstack.project missing" .Values.netns.openstack.project }}
      region: {{ required ".Values.global.region missing" .Values.global.region }}