kind: Secret
apiVersion: v1

metadata:
  name: neutron-ns-prober
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
  password: {{ required ".Values.nsprober.password missing" .Values.nsprober.password | b64enc }}
