apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: r-{{ .Values.global.region }}
spec:
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: r-{{ .Values.global.region }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: IroncoreMetalCluster
    name: r-{{ .Values.global.region }}
