apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: IroncoreMetalCluster
metadata:
  name: r-{{ .Values.global.region }}
spec:
  controlPlaneEndpoint:
    host: {{ .Values.controlPlane.address }}
    port: {{ .Values.controlPlane.port }}
