kind: KubeadmControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
metadata:
  name: r-{{ .Values.global.region }}
spec:
  replicas: {{ default 3 .Values.controlPlane.replicas }}
  machineTemplate:
    infrastructureRef:
      kind: IroncoreMetalMachineTemplate
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
      name: r-{{ .Values.global.region }}
  kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        name: $${METAL_HOSTNAME}
        kubeletExtraArgs:
          cloud-provider: external
        taints: []
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
          secure-port: "6443"
      controllerManager:
        extraArgs:
          cloud-provider: external
          allocate-node-cidrs: "true"
      dns:
        imageRepository: {{ .Values.images.dns.repository }}
        imageTag: {{ .Values.images.dns.tag }}
      networking:
        dnsDomain: cluster.local
        podSubnet: {{ .Values.controlPlane.podSubnet }}
        serviceSubnet: {{ .Values.controlPlane.serviceSubnet }}
      imageRepository: {{ .Values.images.repository }}
    joinConfiguration:
      nodeRegistration:
        name: $${METAL_HOSTNAME}
        kubeletExtraArgs:
          cloud-provider: external
        taints: []
    files:
    - content: |
        apiVersion: v1
        kind: Pod
        metadata:
          creationTimestamp: null
          name: kube-vip
          namespace: kube-system
        spec:
          containers:
          - args:
            - manager
            env:
            - name: vip_arp
              value: "true"
            - name: port
              value: "6443"
            - name: vip_interface
              value: ""
            - name: vip_cidr
              value: "32"
            - name: cp_enable
              value: "true"
            - name: cp_namespace
              value: kube-system
            - name: vip_ddns
              value: "false"
            - name: svc_enable
              value: "true"
            - name: svc_leasename
              value: plndr-svcs-lock
            - name: svc_election
              value: "true"
            - name: vip_leaderelection
              value: "true"
            - name: vip_leasename
              value: plndr-cp-lock
            - name: vip_leaseduration
              value: "15"
            - name: vip_renewdeadline
              value: "10"
            - name: vip_retryperiod
              value: "2"
            - name: address
              value: {{ .Values.controlPlane.address }}
            - name: prometheus_server
              value: :2112
            image: {{ .Values.images.kubeVip.repository }}:{{ .Values.images.kubeVip.tag }}
            imagePullPolicy: IfNotPresent
            name: kube-vip
            resources: {}
            securityContext:
              capabilities:
                add:
                - NET_ADMIN
                - NET_RAW
            volumeMounts:
            - mountPath: /etc/kubernetes/admin.conf
              name: kubeconfig
            - mountPath: /etc/hosts
              name: etchosts
          hostNetwork: true
          volumes:
          - hostPath:
              path: /etc/kubernetes/admin.conf
            name: kubeconfig
          - hostPath:
              path: /etc/kube-vip.hosts
              type: File
            name: etchosts
        status: {}
      owner: root:root
      path: /etc/kubernetes/manifests/kube-vip.yaml
      permissions: "0644"

    - content: 127.0.0.1 localhost kubernetes
      owner: root:root
      path: /etc/kube-vip.hosts
      permissions: "0644"

    format: ignition
    ignition:
      containerLinuxConfig:
        additionalConfig: |-
{{ tpl .Values.controlPlane.additionalConfig . | indent 10 }}

    users:
      - name: {{ $.Values.user.name }}
        passwd: {{ $.Values.user.passwordhash }}
        groups: "sudo"
        sshAuthorizedKeys:
        - {{ $.Values.user.key | quote }}
    preKubeadmCommands:
     - hostnamectl set-hostname $${METAL_HOSTNAME}
  version: {{ .Values.controlPlane.version }}
