apiVersion: v1
kind: Secret
metadata:
  name: vcenter-operator
  labels:
    {{- tuple . "vcenter-operator" "operator" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | nindent 4 }}
data:
  namespace: {{ .Values.global.keystoneNamespace | b64enc }}
  username: {{ .Values.username | include "resolve_secret" | b64enc }}
  password: {{ .Values.global.vcenter_operator_master_password | include "resolve_secret" | b64enc }}
  tsig_key: {{ .Values.tsig_key | include "resolve_secret" | b64enc }}
  vault_url: {{ .Values.vault_url | b64enc }}
  mount_path: {{ .Values.mount_path | b64enc }}
  role_id: {{ .Values.role_id | include "resolve_secret" | b64enc }}
  secret_id: {{ .Values.secret_id | include "resolve_secret" | b64enc }}
  ad_ttu_username: {{ .Values.ad_ttu_username | include "resolve_secret" | b64enc }}
  ad_ttu_password: {{ .Values.ad_ttu_password | include "resolve_secret" | b64enc }}
{{- range $key, $value := .Values.variables }}
  {{ $key }}: {{ $value | include "resolve_secret" | b64enc }}
{{- end }}
