groups:
  - name: manila-maia
    rules:
      - alert: AbsentNetAppVolumeTotalOpsMaia
        expr: absent(netapp_volume_total_ops:maia)
        for: 30m
        labels:
          severity: info
          context: maia
          service: manila
          tier: os
          support_group: compute-storage-api
          support_component: manila_netapp
        annotations:
          description: Metrics `netapp_volume_total_ops:maia` missing
          summary: Metrics `netapp_volume_total_ops:maia` missing

      # - alert: AbsentNetAppSnapmirrorLabelsMaia
      #   expr: absent(netapp_snapmirror_labels:maia{region=~"qa-de-1|ap-ae-1|ap-au-1|ap-cn-1|ap-jp-1|na-ca-1|na-us-1|na-us-2|na-us-3|eu-nl-1|eu-de-1|eu-de-2"})
      #   for: 30m
      #   labels:
      #     severity: info
      #     context: maia
      #     service: manila
      #     tier: os
      #     support_group: compute-storage-api
      #     support_component: manila_netapp
      #   annotations:
      #     description: Metrics `netapp_snapmirror_labels:maia` missing
      #     summary: Metrics `netapp_snapmirror_labels:maia` missing
