global:
  region: regionOne
  domain: evil.corp

ingress:
  tls_client_auth:
    cacrt: |
      -----BEGIN CERTIFICATE-----
      superSecretCertificate
      -----END CERTIFICATE-----

kube-fip-controller:
  openstack:
    authURL: https://keystone.evil.corp:5000/v3
    regionName: regionOne
    username: admin
    userDomainName: Default
    password: topSecret!
    projectName: myProject
    projectDomainName: Default

    # Name of the floating network and subnet used for creating floating IPs.
    defaultFloatingNetworkName: floating-network
    defaultFloatingSubnetName: floating-subnet

digicert-issuer:
  provisioner:
    validityYears: 1
    disableRenewalNotifications: true
    skipApproval: true
    paymentMethod: "balance"
    orderType: "private_ssl_plus"
    apiToken: "superSecret!"
    caCertID: "AB123456"
    organizationID: 1
    organizationName: "ECorp"
    organizationUnits:
      - someOrgUnit

maintenance-controller:
  enabled: false

ldap-named-user:
  ldapUrl: https://top.secret
  ldapBindUser: secret!
  ldapBaseOu: secret!
  ldapBindPassword: secret!
  ldapAccessFilter: secret!
  sudoersGroup: secret!